#!/bin/bash
#
# Script ultra-mega-temporário para publicar o sislegis.war no ambiente de homologação

ORIGEM=target/sislegis.war
DESTINO=54480d435973ca7073000316@sislegis-pensandoodireito.rhcloud.com:~/wildfly/standalone/deployments/ROOT.war

if ! [ -f "$ORIGEM" ]
then
    echo "Cadê o pacote ($ORIGEM)!?"
    exit
fi

scp $ORIGEM $DESTINO
